###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Alberto Cardozo",
  "age": 68,
  "email": "alberto@email.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/6137e2bb2e329eb206b0073e HTTP/1.1

###
DELETE http://localhost:9000/api/users/6137e1725461c36eba8b2ce4 HTTP/1.1

###
PUT http://localhost:9000/api/users/6137e2412e329eb206b0073c HTTP/1.1
Content-Type: application/json

{
  "name": "John Conway",
  "age": 80,
  "email": "johnconway@email.com"
}

###
POST http://localhost:9000/api/servicios HTTP/1.1
Content-Type: application/json

{
  "name": "DNS 192.168.10.10",
  "dominio": "dns.corpoelec.com"
}

###
POST http://localhost:9000/api/servicios HTTP/1.1
Content-Type: application/json

{
  "name": "Correo Web",
  "dominio": "correo.corpoelec.com"
}


###
POST http://localhost:9000/api/servicios HTTP/1.1
Content-Type: application/json

{
  "name": "Intranet",
  "dominio": "intranet.corpoelec.com"
}

###
POST http://localhost:9000/api/servicios HTTP/1.1
Content-Type: application/json

{
  "name": "Correo Thunderbird",
  "dominio": "thunderbird.corpoelec.com"
}


###
GET http://localhost:9000/api/servicios HTTP/1.1
